name: LaTeX to PDF

on:
  push:
    paths:
      - "**.json"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository 🦑
        uses: actions/checkout@v2
      # - name: JSON => LaTeX
        using: 'node12'
        main: 'index.js'
        working_directory: cv
      - name: LaTeX => PDF 📋
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: cv
          root_file: cv.tex
      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: cv
