name: LaTeX to PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'resume/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository 🦑
        uses: actions/checkout@v5

      # - name: JSON => LaTeX
        # using: 'node12'
        # main: 'index.js'
        # working_directory: resume

      - name: LaTeX => PDF 📋
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: resume
          root_file: resume.tex

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: resume
